translations_es = {"Adventure": "Aventuras",
                   "Animation": "Animación",
                   "Children": "Niños",
                   "Comedy": "Comedia",
                   "Fantasy": "Fantasía",
                   "Romance": "Romance",
                   "Drama": "Drama",
                   "Action": "Acción",
                   "Crime": "Crimen",
                   "Thriller": "Novela de suspenso",
                   "Horror": "Horror",
                   "Mystery": "Misterio",
                   "Sci-Fi": "Ciencia ficción",
                   "War": "Guerra",
                   "Musical": "Musical",
                   "Documentary": "Documental",
                   "IMAX": "IMAX",
                   "Western": "Occidental",
                   "Film-Noir": "Cine-noir"}

translations_se = {"Adventure": "Äventyr",
                   "Animation": "Animering",
                   "Children": "Barn",
                   "Comedy": "Komedi",
                   "Fantasy": "Fantasi",
                   "Romance": "Romantik",
                   "Drama": "Drama",
                   "Action": "Verkan",
                   "Crime": "Brottslighet",
                   "Thriller": "Thriller",
                   "Horror": "Skräck",
                   "Mystery": "Mysterium",
                   "Sci-Fi": "Sci-Fi",
                   "War": "Krig",
                   "Musical": "Musikalisk",
                   "Documentary": "Dokumentär",
                   "IMAX": "IMAX",
                   "Western": "Västra",
                   "Film-Noir": "Film Noir"}
