translations_en = {"Adventure": "Adventure",
                   "Animation": "Animation",
                   "Children": "Children",
                   "Comedy": "Comedy",
                   "Fantasy": "Fantasy",
                   "Romance": "Romance",
                   "Drama": "Drama",
                   "Action": "Action",
                   "Crime": "Crime",
                   "Thriller": "Thriller",
                   "Horror": "Horror",
                   "Mystery": "Mystery",
                   "Sci-Fi": "Sci-Fi",
                   "War": "War",
                   "Musical": "Musical",
                   "Documentary": "Documentary",
                   "IMAX": "IMAX",
                   "Western": "Western",
                   "Film-Noir": "Film-Noir"}

translations_es = {"Adventure": "Aventuras",
                   "Animation": "Animación",
                   "Children": "Niños",
                   "Comedy": "Comedia",
                   "Fantasy": "Fantasía",
                   "Romance": "Romance",
                   "Drama": "Drama",
                   "Action": "Acción",
                   "Crime": "Crimen",
                   "Thriller": "Novela de suspenso",
                   "Horror": "Horror",
                   "Mystery": "Misterio",
                   "Sci-Fi": "Ciencia ficción",
                   "War": "Guerra",
                   "Musical": "Musical",
                   "Documentary": "Documental",
                   "IMAX": "IMAX",
                   "Western": "occidental",
                   "Film-Noir": "Cine-noir"}

translations_se = {"Adventure": "Ã„ventyr",
                   "Animation": "Animering",
                   "Children": "Barn",
                   "Comedy": "Komedi",
                   "Fantasy": "Fantasi",
                   "Romance": "romantik",
                   "Drama": "Drama",
                   "Action": "Verkan",
                   "Crime": "Brottslighet",
                   "Thriller": "Thriller",
                   "Horror": "SkrÃ¤ck",
                   "Mystery": "Mysterium",
                   "Sci-Fi": "Sci-Fi",
                   "War": "Krig",
                   "Musical": "Musikalisk",
                   "Documentary": "DokumentÃ¤r",
                   "IMAX": "IMAX",
                   "Western": "VÃ¤stra",
                   "Film-Noir": "Film noir"}
